### ISSUE TITLE
[BUG] databricks docker missing numpy, pandas, pyarrow, and psycopg2

### ISSUE THREAD

**Issue by tgravescs** [NVIDIA/spark-rapids-container#38]
**Describe the bug**
our databricks docker container is missing basic python libraries numpy, pandas, pyarrow, and psycopg2.  Since these are used a lot by many users we should include them.  One specific customer tried our container and had failures because these missing.

Specific versions in 10.4 and I believe 11.3:

```
numpy==1.20.1 \
pandas==1.2.4 \
pyarrow==4.0.0 \
psycopg2==2.8.5 \

```

**Comment by NVnavkumar** [comment]
Should we only stick to the Databricks-specific versions, or at least try the updated versions of these packages first? The reason is that many of these packages could have security vulnerabilities (particularly of concern is psycopg2 since it makes network connections to databases).

**Comment by tgravescs** [comment]
We need to make sure it’s compatible, the customer who had the issue actually somehow was pulling other versions from another library they installed and they didn’t work.  I would prefer just to keep the versions the same if possible.
