### ISSUE TITLE
[FEA] Alluxio home settings should be pinned in Databricks Docker container

### ISSUE THREAD

**Issue by NVnavkumar** [NVIDIA/spark-rapids-container#43]
**Is your feature request related to a problem? Please describe.**
When using Alluxio in the Databricks Docker container, we require the user to set both `ALLUXIO_HOME` environment variables and the Spark configuration `spark.rapids.alluxio.home`. These should be unnecessary as the version of Alluxio is fixed inside the Docker container image.

**Describe the solution you'd like**
The `ALLUXIO_HOME` environment variable should be set in the Docker container's built-in init script. This can done during the Docker build process using a `sed` command inside the Dockerfile. The documentation should be updated to not require this setting. Also, for `spark.rapids.alluxio.home`, maybe the code itself can read `ALLUXIO_HOME` as a possible default value here (then we can file a corresponding issue in https://github.com/NVIDIA/spark-rapids`) or this setting can be added via `sed` command in the Dockerfile to update `00-custom-spark-driver-defaults.conf`. Therefore the user should not be fully concerned with knowing the exact Alluxio paths, it should just work if `ENABLE_ALLUXIO=1`

**Comment by tgravescs** [comment]
Sounds like we missed updating some things with https://github.com/NVIDIA/spark-rapids/pull/7844. I agree ALLUXIO_HOME should just go away and not be needed by the end user. As long as we create the symlink we shouldn't need to explicitly set spark.rapids.alluxio.home since we should be setting up to use the default location.  Is there an issue with that?

**Comment by NVnavkumar** [comment]
We should at least create the symlink in the Dockerfile and remove the instructions to set ALLUXIO_HOME.  Reading from ALLUXIO_HOME in the plugin itself I think should also be done, but is lower priority.

**Comment by res-life** [comment]
#39  already created a link.
I agree ALLUXIO_HOME should just go away. Need further discussion.
I posted a PR to update the doc, please review. 
@NVnavkumar
